/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import Datos.ModeloUsuarios;
import Metodos.MetodosInicioSesion;

/**
 *
 * @author anner
 */
public class Registro extends javax.swing.JFrame {

     ModeloUsuarios m = new ModeloUsuarios();
     MetodosInicioSesion me = new MetodosInicioSesion();
     /**
      * Creates new form IniciarSesion
      */
     public Registro() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT
      * modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jLabel6 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          txtPass = new javax.swing.JPasswordField();
          txtCorreo = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          txtApellidos = new javax.swing.JTextField();
          txtNombres = new javax.swing.JTextField();
          jLabel1 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          txtConfirmPass = new javax.swing.JPasswordField();
          jLabel7 = new javax.swing.JLabel();
          jButton1 = new javax.swing.JButton();
          jLabel8 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("REGISTRO");
          setBackground(new java.awt.Color(255, 255, 255));

          jPanel1.setBackground(new java.awt.Color(255, 255, 255));
          jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 66, 184)));
          jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\anner\\Desktop\\Universidad Mariano Galvez\\Cuarto Semestre\\Programacion II\\Homeworks\\MiniPokedex\\src\\main\\java\\Imagenes\\Pikachu.png")); // NOI18N
          jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 26, -1, 128));

          jLabel4.setText("Contraseña :");
          jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

          txtPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 150, 220), 1, true));
          jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 275, 23));

          txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 150, 220), 1, true));
          txtCorreo.setCaretColor(new java.awt.Color(255, 0, 0));
          jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 275, 23));

          jLabel3.setText("Correo :");
          jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

          jLabel2.setText("Apellidos :");
          jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

          txtApellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 150, 220), 1, true));
          txtApellidos.setCaretColor(new java.awt.Color(255, 0, 0));
          jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 275, 23));

          txtNombres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 150, 220), 1, true));
          txtNombres.setCaretColor(new java.awt.Color(255, 0, 0));
          jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 275, 23));

          jLabel1.setText("Nombres :");
          jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 74, -1));

          jLabel5.setText("Confirma tu contraseña :");
          jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

          txtConfirmPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 150, 220), 1, true));
          txtConfirmPass.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtConfirmPassActionPerformed(evt);
               }
          });
          jPanel1.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 275, 23));

          jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
          jLabel7.setText("INGRESA TUS DATOS");
          jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 78, -1, -1));

          jButton1.setBackground(new java.awt.Color(51, 153, 255));
          jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
          jButton1.setText("REGISTRARSE");
          jButton1.setBorderPainted(false);
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });
          jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, 30));

          jLabel8.setText("Regresar a Inicio de Sesion");
          jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel8MouseClicked(evt);
               }
          });
          jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 406, 130, -1));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
          );

          pack();
          setLocationRelativeTo(null);
     }// </editor-fold>//GEN-END:initComponents

     private void txtConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPassActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtConfirmPassActionPerformed

     private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
          // TODO add your handling code here:
          InicioSesion form = new InicioSesion();
          form.setVisible(true);
     }//GEN-LAST:event_jLabel8MouseClicked

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // TODO add your handling code here:
          
          m.setNombres(txtNombres.getText());
          m.setApellidos(txtApellidos.getText());
          if(me.ValidarCorreo(txtCorreo.getText())){
               m.setCorreo(txtCorreo.getText());
          }
          if(me.CompararPass(txtPass.getText(), txtConfirmPass.getText())){
               m.setPassword(me.Encriptador(txtPass.getText(),10));
          }
          
     }//GEN-LAST:event_jButton1ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new Registro().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JTextField txtApellidos;
     private javax.swing.JPasswordField txtConfirmPass;
     private javax.swing.JTextField txtCorreo;
     private javax.swing.JTextField txtNombres;
     private javax.swing.JPasswordField txtPass;
     // End of variables declaration//GEN-END:variables
}
